### ISSUE TITLE
Issue with Adding sync-cordova-plugin

### ISSUE THREAD

**Issue by rajc3340** [cloudant/sync-cordova-plugin#100]
Hello, 
I am trying to add the "sync-cordova-plugin" to my Ionic project. When I execute the following command, I get errors and I can't get going. Any help on this would be greatly appreciated, this is extremely urgent.  We had it working in the past when we added the plugin several months. Several individuals on the team tried this and we all get the error.

**cordova plugin add https://github.com/cloudant/sync-cordova-plugin#0.4.0**

_**Note**_ : I also tried 0.3.0 and 0.4.1 and get the same error.

****************************************************************************************
**_For reference here is my current setup:_**
 
C:\Development\Sandbox>ionic info
cli packages: (C:\Users\XXXXX\AppData\Roaming\npm\node_modules)
    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:
    cordova (Cordova CLI) : 8.0.0

local packages:
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:
    Android SDK Tools : 26.1.1
    Node              : v8.9.4
    npm               : 5.6.0
    OS                : Windows 10

**_Note_** We tried different versions of Cordova also.
****************************************************************************************

**_Error_**
Failed to install 'cloudant-sync': CordovaError: Failed to fetch plugin cordova-plugin-file via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
    at C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:173:37
    at _rejected (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:864:24)
    at C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:808:41)
    at C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:137:13)
    at flush (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Failed to restore plugin "cloudant-sync" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin cordova-plugin-file via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module

**Comment by ricellis** [comment]
> Failed to fetch plugin **cordova-plugin-file** via registry.

Seems like it can't find the `cordova-plugin-file` dependency, you could try the `--nofetch` flag to revert to the older style fetch behaviour for Cordova.

Just to be clear are you running `ionic cordova...` or just `cordova...`? It seems like there are a lot of issues like this around related to the ionic wrapped versions of the commands.

**Comment by rajc3340** [comment]
Thanks for looking into it.
I tried --nofetch also, and get the same result. And yes I did execute ionic cordova.....

I forgot to add this earlier, when I execute the command from command line I get the error I mentioned before. However when I look inside the "plugins" folder of the project I see the folder with "cloudant-sync" and several sub folders and files (similar structure to what I would get with git clone, contents are different). Additionally the package.json and config.xml file(s) are not getting updated accordingly.

**Comment by ricellis** [comment]
As per issues like [this](https://github.com/ionic-team/ionic-cli/issues/2716) I would recommend trying the `cordova` commands rather than `ionic cordova`

**Comment by rajc3340** [comment]
I tried both options and have the same issue

**Comment by rajc3340** [comment]
_**ionic cordova plugin add https://github.com/cloudant/sync-cordova-plugin#0.4.0 --nofetch**_
> cordova plugin add https://github.com/cloudant/sync-cordova-plugin#0.4.0 --save
Installing "cloudant-sync" for android

Failed to install 'cloudant-sync': CordovaError: Failed to fetch plugin cordova-plugin-file via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
    at C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:173:37
    at _rejected (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:864:24)
    at C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:808:41)
    at C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:137:13)
    at flush (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

(node:7064) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Failed to fetch plugin cordova-plugin-file via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
(node:7064) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

***************************************************************
_**cordova plugin add https://github.com/cloudant/sync-cordova-plugin#0.4.0 --nofetch**_
Installing "cloudant-sync" for android
Failed to install 'cloudant-sync': CordovaError: Failed to fetch plugin cordova-plugin-file via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
    at C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:173:37
    at _rejected (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:864:24)
    at C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:808:41)
    at C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:137:13)
    at flush (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:7536) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Failed to fetch plugin cordova-plugin-file via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
(node:7536) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by cmijum** [comment]
Hi ricellis, 
Same issue here..  if we remove the plugin and try to add it again it's not getting added 

**cordova plugin add https://github.com/cloudant/sync-cordova-plugin#0.4.1**

**ERROR !**
Error: Failed to fetch plugin https://github.com/cloudant/sync-cordova-plugin#0.4.1 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! git submodule -q update --init --recursive: fatal: 'submodule' appears to be a git command, but we were not
npm ERR! git submodule -q update --init --recursive: able to execute it. Maybe git-submodule is broken?
npm ERR! git submodule -q update --init --recursive:
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\cmijum\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
 "https://github.com/cloudant/sync-cordova-plugin#0.4.1" "--production" "--save"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true submodule -q update --init --recursive
npm ERR! fatal: 'submodule' appears to be a git command, but we were not
npm ERR! able to execute it. Maybe git-submodule is broken?
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Git Projects\fn_mobile_investigation\FNInvestigation\npm-debug.log

[ERROR] An error occurred while running cordova plugin add https://github.com/cloudant/sync-cordova-plugin#0.4.1 --save
        (exit code 1).

**Comment by emlaver** [comment]
I've created an ionic sample project from scratch.  Here are the commands I used:
```
npm install -g ionic
ionic start myApp tabs
cd myApp (created from line above)
cordova plugin add https://github.com/cloudant/sync-cordova-plugin#0.4.1
```

output of `ionic info`:
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.4
    Node              : v8.10.0
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.1 Build version 9B46 

Environment Variables:

    ANDROID_HOME : /Users/estebanmlaver/Library/Android/sdk/

Misc:

    backend : pro
```

My `package.json`:
```
{
  "name": "myApp",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/animations": "5.2.9",
    "@angular/common": "5.2.9",
    "@angular/compiler": "5.2.9",
    "@angular/compiler-cli": "5.2.9",
    "@angular/core": "5.2.9",
    "@angular/forms": "5.2.9",
    "@angular/http": "5.2.9",
    "@angular/platform-browser": "5.2.9",
    "@angular/platform-browser-dynamic": "5.2.9",
    "@ionic-native/core": "4.5.3",
    "@ionic-native/splash-screen": "4.5.3",
    "@ionic-native/status-bar": "4.5.3",
    "@ionic/pro": "1.0.20",
    "@ionic/storage": "2.1.3",
    "cloudant-sync": "git+https://github.com/cloudant/sync-cordova-plugin.git#0.4.1",
    "cordova-android": "^7.0.0",
    "cordova-plugin-device": "^2.0.1",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^1.1.16",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "rxjs": "5.5.7",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.20"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.8",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cloudant-sync": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {}
    },
    "platforms": [
      "android"
    ]
  }
}
```

**Comment by rajc3340** [comment]
@emlaver , I followed your instructions and it worked for me.  
I then added the android platform.
But as a next step to build the app I ran the command _**ionic cordova build android**_. This command fails with errors below... **Any help on this would be greatly appreciated, as we are stuck here.**

................
.................
:app:compileDebugJavaWithJavac
C:\Development\myApp\platforms\android\app\src\main\java\io\ionic\keyboard\IonicKeyboard.java:131: error: cannot find symbol
        rootView.getViewTreeObserver().removeOnGlobalLayoutListener(list);
                                      ^
  symbol:   method removeOnGlobalLayoutListener(OnGlobalLayoutListener)
  location: class ViewTreeObserver
C:\Development\myApp\platforms\android\app\src\main\java\org\apache\cordova\file\FileUtils.java:97: error: cannot find symbol
            Manifest.permission.READ_EXTERNAL_STORAGE,
                               ^
  symbol:   variable READ_EXTERNAL_STORAGE
  location: class permission
C:\Development\myApp\platforms\android\app\src\main\java\org\apache\cordova\file\FileUtils.java:554: error: cannot find symbol
        PermissionHelper.requestPermission(this, requestCode, Manifest.permission.READ_EXTERNAL_STORAGE);
                                                                                 ^
  symbol:   variable READ_EXTERNAL_STORAGE
  location: class permission
C:\Development\myApp\platforms\android\app\src\main\java\org\apache\cordova\file\FileUtils.java:563: error: cannot find symbol
        return PermissionHelper.hasPermission(this, Manifest.permission.READ_EXTERNAL_STORAGE);
                                                                       ^
  symbol:   variable READ_EXTERNAL_STORAGE
  location: class permission
C:\Development\myApp\platforms\android\app\src\main\java\org\apache\cordova\file\LocalFilesystem.java:422: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                                                        ^
  symbol:   variable LOLLIPOP
  location: class VERSION_CODES
C:\Development\myApp\platforms\android\app\src\main\java\org\apache\cordova\file\LocalFilesystem.java:424: error: cannot find symbol
            for (File f : context.getExternalMediaDirs()) {
                                 ^
  symbol:   method getExternalMediaDirs()
  location: variable context of type Context
C:\Development\myApp\platforms\android\app\src\main\java\org\apache\cordova\splashscreen\SplashScreen.java:371: error: cannot find symbol
                if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.LOLLIPOP) {
                                                                                      ^
  symbol:   variable LOLLIPOP
  location: class VERSION_CODES
C:\Development\myApp\platforms\android\app\src\main\java\org\apache\cordova\splashscreen\SplashScreen.java:388: error: cannot find symbol
                        progressBar.setIndeterminateTintList(colorStateList);
                                   ^
  symbol:   method setIndeterminateTintList(ColorStateList)
  location: variable progressBar of type ProgressBar
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
8 errors


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by ricellis** [comment]
The errors you are reporting appear to be coming from `io.ionic` and `org.apache.cordova` files, nothing specific to this sync-cordova-plugin. From the symbols reported as missing it would appear that the Android API level required for your chosen platform is probably lower than that available/specified by your build environment. However, I'm afraid that we are unable to debug the Ionic framework or your build environment. If you are able to identify a specific reproducible issue relating to the sync-cordova-plugin itself then we can try to look into it further.

If it helps the plugin was tested with:
* Android 7.0, API 24, revision 2
* Android SDK Build-tools, revision 26.0.1
* Oracle JDK8 1.8.0_144
* node v6.12.2 (npm v3.10.10)
* cordova@7.1.0
* cordova-android@6.3.0

@emlaver FYI ^
